### ISSUE TITLE
System Modeller Version is not Currently Displayed Inside the System Modeller GUI

### ISSUE THREAD

**Issue by samuelsenior** [Spyderisk/system-modeller#151] opened 2024-03-18 10:54 UTC
The System Modeller version is not currently displayed inside the System Modeller GUI, though it would be useful for it to be displayed somewhere within it.

**Comment by scp93ch** [comment] 2024-03-19 21:18
Neither the system-modeller service or the web UI currently have any knowledge of their versions so cannot display it. The version number is generally set when we make a release. We need to work out:

- the best process for a release now we are on GitHub 
- how to store a version number in the client and service (or just the service initially?)
- whether setting the version can be automatically synchronised in the release process

Ideally we'd want a separate version number for the service and client. Currently they are in the same repository but they are separate pieces of software.

**Comment by danshearer** [comment] 2024-07-22 15:26
@scp93ch wrote:

> we need to work out the best process for a release now we are on GitHub

Some progress... that's now in Issue #185 , "Release process" .

> how to store a version number in the client and service (or just the service initially?)

I propose we have files called something like "version-of-service.java" and "version-of-client.js" which are updated by manually invoking a script as part of the release process.

> whether setting the version can be automatically synchronised in the release process

We are already using version tags in the completely different [system-modeller-docs release process](https://github.com/Spyderisk/system-modeller-docs/blob/main/scripts/build-spyderisk-mkdocs.sh) and we might do the same in system-modeller. Thoughts?

A handy list of things to remember is at the [versioning page on reproducible-builds.org](https://reproducible-builds.org/docs/version-information/).

**Comment by danshearer** [comment] 2024-07-22 15:30
Specifically, should "version-of-service.java" etc files be created from the value of gradle environment variables?

**Comment by scp93ch** [comment] 2024-07-22 15:46
The version of the system modeller was added in https://github.com/Spyderisk/system-modeller/pull/187 / #68.

The version is pulled from the tag chosen at the point of making a release and is placed into the docker image that is built in an environment variable which is picked up by the service and provided to the client UI via a new API call.

This might therefore be a duplicate.

**Comment by danshearer** [comment] 2024-07-22 15:47
> This might therefore be a duplicate.

If it is (and I agree it looks like it) then please can you close?

**Comment by scp93ch** [comment] 2024-07-22 15:56
It is a duplicate, so I am marking it as such and closing. It's only a duplicate because I subverted a different issue to get the version added 😄

**Closed by scp93ch** 2024-07-22 15:56 UTC
Labels: enhancement
